name: Empty env MWE

on:
  pull_request: {}
  push: {}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          env | grep "^GITHUB_"
      - run: |
          set -euxo pipefail
          [[ -n "$GITHUB_HEAD_REF" ]] &&
          [[ -n "$GITHUB_BASE_REF" ]] &&
          [[ -n "$GITHUB_SHA" ]] &&
          true
